name: learn_programtion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  shared_preferences: ^2.2.3
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  easy_localization: ^3.0.7
  cached_network_image: ^3.4.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  motion_tab_bar_v2: ^0.3.0
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.2.0
  flutter_custom_clippers: ^2.1.0
  get_it: ^8.0.3
  url_launcher: ^6.3.1
  youtube_player_flutter: ^8.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/
  fonts:
     - family: Alexandria
       fonts:
         - asset: assets/fonts/Alexandria-VariableFont_wght.ttf
         - asset: assets/fonts/Alexandria-Medium.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

